### ISSUE TITLE
爱奇艺和腾讯视频抓到的cookie怎么放阿

### ISSUE THREAD

**Issue by yangzhicong** [chenyouxiu/py_qiandao#1]
抓好的cookie都不知道怎么用，也没有文件说明

**Comment by chenyouxiu** [comment]
大哥推荐你去别人那边  我这个是用青龙面板的

**Comment by chenyouxiu** [comment]
`P00001 = os.environ.get('AQY_P00001')`或者你把这行修改成
`P00001 =“”`后面放你抓的P00001就行了

**Comment by yangzhicong** [comment]
我liunx服务器跑，按大佬的提示成功跑起来了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenyouxiu/py_qiandao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenyouxiu/py_qiandao] 爱奇艺和腾讯视频抓到的cookie怎么放阿 (#1)





 
P00001 = os.environ.get('AQY_P00001')或者你把这行修改成
 P00001 =“”后面放你抓的P00001就行了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhicong** [comment]
爱奇艺的搞定了，但腾讯视频的cookie填在tx_cookie = ' '里报错
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenyouxiu/py_qiandao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenyouxiu/py_qiandao] 爱奇艺和腾讯视频抓到的cookie怎么放阿 (#1)





 
P00001 = os.environ.get('AQY_P00001')或者你把这行修改成
 P00001 =“”后面放你抓的P00001就行了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyouxiu** [comment]
https://github.com/sy-records/v-checkin
你去看这个大哥的吧  我拿这个大哥的  你可以看他抓包往我这里面直接填就可以跑

**Comment by funnylook** [comment]
> `P00001 = os.environ.get('AQY_P00001')`或者你把这行修改成 `P00001 =“”`后面放你抓的P00001就行了

改了之后报错怎么回事。。。
## 开始执行... 2022-07-16 18:28:56

Traceback (most recent call last):
  File "/ql/data/scripts/raw_main_py_AQY.py", line 290, in <module>
    msg1 = obj.sign()
  File "/ql/data/scripts/raw_main_py_AQY.py", line 51, in sign
    growth = res.json()[
KeyError: 'signInfo'

## 执行结束... 2022-07-16 18:28:57 耗时 1 秒
